### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by MoonShadowIllusion** [QIN2DIM/armour-geetest#1]
ImportError: cannot import name 'URLS_GT2' from 'examples.demo_geetest2' (C:\Users\xuke\Desktop\armour-geetest-main\examples\demo_geetest2.py)

我的py版本是3.9，pycharm2021.2，python真实环境

**Comment by QIN2DIM** [comment]
~内伤了，我忘记移除examples的__init__.py的索引关系了。我等会操作一下重新传个版本。~
bug已修复， 'URLS_GT2'列表从原来的路径移动到`main.py`之中了，而examples并不在重构索引的目标范围内- -漏检了。

**Comment by QIN2DIM** [comment]
URLS_GT2是演示站点的链接

**Comment by QIN2DIM** [comment]
已更新，`c7ef6e7`版本已经调整demo的索引关系了
